version: '3.9'
networks:
  user.data_network:
    name: redis_network
  rabbitmq_network:
    name: rabbit_network
  sql.data_network:
    name: database_network
  web_network:
    name: web_network


services:

  # Service redis 
  user.data:
    image: redis:latest
    container_name: redis-container
    # restart: on-failure
    ports: 
      - 6379:6379
    networks:
      - user.data_network
    depends_on:
      - sql.data
  
  # Service Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_network
    depends_on:
      - sql.data
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  # Service base de données
  sql.data:
    image: azed01/appscore:database
    container_name: sql.data
    restart: on-failure
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Pass@word
    networks:
     - sql.data_network
    volumes:
     - D:\appscore\data:/var/opt/mssql/data/
  
  # Service applicants
  applicants.api:
    image: azed01/appscore:applicants
    container_name: applicants
    restart: on-failure
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants
      - HostRabbitmq=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sql.data_network
      - rabbitmq_network
      - user.data_network
      - web_network
    ports:
      - 8081:80

  # Service jobs
  jobs.api:
    image: azed01/appscore:jobs
    container_name: service-api-jobs
    restart: on-failure
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs
      - HostRabbitmq=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sql.data_network
      - rabbitmq_network
      - user.data_network
      - web_network
    ports: 
      - 8083:80
    

  # Service identity
  identity.api:
    image: azed01/appscore:identity
    container_name: service-api-identity
    restart: on-failure
    environment:
     - RedisHost=user.data:6379
     - HostRabbitmq=rabbitmq
    networks:
     - sql.data_network
     - user.data_network
     - rabbitmq_network
     - web_network
    depends_on:
     rabbitmq:
       condition: service_healthy
    ports:
     - 8084:80
    

  # Service Web    
  web:
    image: azed01/appscore:web
    ports:
      - 8080:80 
    depends_on:
      - applicants.api
      - jobs.api
      - identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - web_network
    container_name: web